### ISSUE TITLE
Stable Clustering / Incremental Clustering

### ISSUE THREAD

**Issue by ruiwanguk** [spectra-cluster/spectra-cluster-hadoop#1]
To make sure our Hadoop pipeline can scale going forward, and also be able to cluster all the unidentified spectra, I would suggest we extend our existing pipeline to perform stable clustering/ incremental clusterings.

Here are the proposed extensions:

1. Covert all spectra to clusters, also add an unique cluster id and filter out unwanted spectra. (NEW)
2. Major peak clustering, the current job needs to be extended to be able to take two folders as the input. One contains the results from the previous clustering run, another one is produced by step 1. (Modified)
3. Clustering by group clusters with the same id. The idea of this job is to avoid cluster duplications. This job requires all clustering engines (ClusteringEngine and IncrementalClusteringEngine) are able to preserve larger cluster id when merging clusters. (NEW)
4. Merge by precursor m/z window (Unchanged)
5. Merge by shifted precursor m/z window (Unchanged) 
6. Output clusters (Unchanged)

Let me know what you think. I have a prototype already, if this is fine for you, I will do some testing and a pull request.

**Comment by ruiwanguk** [comment]
@jgriss look forward to your feedbacks. Let me know if you want to have a quick chat.

**Comment by jgriss** [comment]
@ruiwanguk I think it's a very good idea.
The only change I'd make is to remove the major peak clustering step.
The reason for this is that we use this first step to create "seeds" for the clustering. But once we do incremental clustering, the initial clusters should already be created and serve as adequate seeds. I'm fairly confident that this will not impede the clustering quality.

**Comment by ruiwanguk** [comment]
pull request created
